KRNL - a kernel for Arduino: krnl.h File Reference
krnl.h File Reference
Data Structures
struct k_t
struct k_msg_t
Macros
#define KRNL_VRS 1238
#define KRNLTMR 1
#define MHZ F16
#define QHD_PRIO 100
#define DMY_PRIO (QHD_PRIO-2)
#define DMY_STK_SZ 90
#define MAIN_PRIO 50
#define STAK_HASH 0x5c
#define MAX_SEM_VAL 50
#define MAX_INT 0x7FFF
#define SEM_MAX_DEFAULT 50
#define lo8(X) ((unsigned char)((unsigned int)(X)))
#define hi8(X) ((unsigned char)((unsigned int)(X) >> 8))
#define K_CHG_STAK()
#define DI() asm volatile ("cli")
#define EI() asm volatile ("sei")
#define RETI() asm volatile ("reti")
#define PUSHREGS()
#define POPREGS()
Functions
char k_eat_time (unsigned int eatTime)
void ki_task_shift (void) __attribute__((naked))
int k_sleep (int time)
struct k_t * k_crt_task (void(*pTask)(void), char prio, char *pStk, int stkSize)
int k_set_prio (char prio)
struct k_t * k_crt_sem (char init_val, int maxvalue)
int k_set_sem_timer (struct k_t *sem, int val)
int ki_signal (struct k_t *sem)
int k_signal (struct k_t *sem)
int k_wait (struct k_t *sem, int timeout)
int k_wait_lost (struct k_t *sem, int timeout, int *lost)
int k_sem_signals_lost (struct k_t *sem)
int ki_nowait (struct k_t *sem)
int ki_wait (struct k_t *sem, int timeout)
int ki_semval (struct k_t *sem)
struct k_msg_t * k_crt_send_Q (int nr_el, int el_size, void *pBuf)
char ki_send (struct k_msg_t *pB, void *el)
char k_send (struct k_msg_t *pB, void *el)
char k_receive (struct k_msg_t *pB, void *el, int timeout, int *lost_msg)
char ki_receive (struct k_msg_t *pB, void *el, int *lost_msg)
int k_tmrInfo (void)
int k_init (int nrTask, int nrSem, int nrMsg)
int k_start (int tm)
int k_stop (int exitVal)
void k_bugblink13 (char on)
int k_stk_chk (struct k_t *t)
int k_unused_stak (struct k_t *t)
char k_set_preempt (char on)
char k_get_preempt (void)
int freeRam (void)
Variables
int k_task
int k_sem
int k_msg
volatile char krnl_preempt_flag
char dmy_stk [DMY_STK_SZ]
struct k_t * task_pool
struct k_t * sem_pool
struct k_t AQ
struct k_t main_el
struct k_t * pAQ
struct k_t * pDmy
struct k_t * pRun
struct k_t * pSleepSem
struct k_msg_t * send_pool
char nr_task
char nr_sem
char nr_send
volatile char k_running
volatile char bugblink
volatile char k_err_cnt
Macro Definition Documentation
#define DI () asm volatile ("cli")
Definition at line 305 of file krnl.h.
Referenced by k_receive(), k_round_robbin(), k_sem_signals_lost(), k_send(), k_set_prio(), k_set_sem_timer(), k_signal(), k_start(), k_stop(), k_unused_stak(), k_wait(), k_wait_lost(), ki_nowait(), ki_receive(), ki_semval(), ki_signal(), and ki_wait().
#define DMY_PRIO (QHD_PRIO-2)
Definition at line 187 of file krnl.h.
Referenced by k_crt_task(), k_init(), and k_set_prio().
#define DMY_STK_SZ 90
Definition at line 188 of file krnl.h.
Referenced by k_init().
#define EI () asm volatile ("sei")
Definition at line 306 of file krnl.h.
Referenced by k_receive(), k_round_robbin(), k_sem_signals_lost(), k_send(), k_set_prio(), k_set_sem_timer(), k_signal(), k_start(), k_stop(), k_unused_stak(), and k_wait().
#define hi8 (X) ((unsigned char)((unsigned int)(X) >> 8))
Definition at line 292 of file krnl.h.
Referenced by k_crt_task().
#define K_CHG_STAK ()
Value:
if (pRun != AQ.next) {  \
  pRun->sp_lo = SPL;    \
  pRun->sp_hi = SPH;    \
  pRun = AQ.next;       \
  SPL = pRun->sp_lo;    \
  SPH = pRun->sp_hi;    \
}
Definition at line 294 of file krnl.h.
Referenced by __attribute__(), and ISR().
#define KRNL_VRS 1238
Definition at line 39 of file krnl.h.
#define KRNLTMR 1
Definition at line 126 of file krnl.h.
Referenced by k_tmrInfo().
#define lo8 (X) ((unsigned char)((unsigned int)(X)))
Definition at line 291 of file krnl.h.
Referenced by k_crt_task().
#define MAIN_PRIO 50
Definition at line 189 of file krnl.h.
#define MAX_INT 0x7FFF
Definition at line 192 of file krnl.h.
#define MAX_SEM_VAL 50
Definition at line 191 of file krnl.h.
#define MHZ F16
Definition at line 131 of file krnl.h.
#define POPREGS ()
Definition at line 434 of file krnl.h.
Referenced by __attribute__(), and ISR().
#define PUSHREGS ()
Definition at line 396 of file krnl.h.
Referenced by __attribute__(), and ISR().
#define QHD_PRIO 100
Definition at line 186 of file krnl.h.
Referenced by k_crt_sem(), and k_init().
#define RETI () asm volatile ("reti")
Definition at line 307 of file krnl.h.
Referenced by __attribute__(), and ISR().
#define SEM_MAX_DEFAULT 50
Definition at line 193 of file krnl.h.
Referenced by k_crt_sem().
#define STAK_HASH 0x5c
Definition at line 190 of file krnl.h.
Referenced by k_crt_task(), and k_unused_stak().
Function Documentation
int freeRam (void)
returns amount of free memory in your system
Definition at line 420 of file krnl.c.
void k_bugblink13 (char on)
Initialise blink on pin 13 ON when dummy is running Nov 2014 - fake do not use it bq it will not work
Definition at line 897 of file krnl.c.
struct k_t* k_crt_sem (char init_val, int maxvalue)
creates a standard Dijkstra semaphore. It can be initialized to values in range [0..maxvalue]
Parameters
[in] init_val startvalue of semaphore 0,1,2,... maxvalue
[in] maxvalue which is maxvalue semaphore can reach
Returns
handle to semaphore or NULL pointer
Remarks
only to be called before start of KRNL
Definition at line 489 of file krnl.c.
References k_t::clip, k_t::cnt1, k_t::cnt2, k_err_cnt, k_running, k_sem, k_t::maxv, k_t::next, nr_sem, k_t::pred, k_t::prio, QHD_PRIO, and SEM_MAX_DEFAULT.
Referenced by k_crt_send_Q(), and k_init().
struct k_msg_t* k_crt_send_Q (int nr_el, int el_size, void * pBuf)
Definition at line 843 of file krnl.c.
References k_msg_t::cnt, k_msg_t::el_size, k_crt_sem(), k_err_cnt, k_msg, k_running, k_sem, k_msg_t::lost_msg, k_msg_t::nr_el, nr_sem, nr_send, k_msg_t::pBuf, k_msg_t::r, k_msg_t::sem, and k_msg_t::w.
struct k_t* k_crt_task (void(*)(void) pTask, char prio, char * pStk, int stkSize)
creates a task and put it in the active Q
Parameters
[in] pTask pointer to function for code (void task(void) ...)
[in] prio Priority 1: highest (QHEAD_PRIO-1): lowest
[in] pStk Reference to data area to be used as stak
[in] stkSize size of data area(in bytes) to be used for stak
Returns
: pointer to task handle or NULL if no success
Remarks
only to be called before start of KRNL but after k_init
Definition at line 346 of file krnl.c.
References k_t::cnt1, k_t::cnt2, k_t::cnt3, DMY_PRIO, hi8, k_err_cnt, k_running, k_task, lo8, k_t::maxv, nr_task, k_t::prio, prio_enQ(), k_t::sp_hi, k_t::sp_lo, and STAK_HASH.
Referenced by k_init().
char k_eat_time (unsigned int eatTime)
Eats CPU time in 1 msec quants
Parameters
[in] eatTime number of milliseconds to eay (<= 10000
just for eating time eatTime in msec's
Definition at line 181 of file krnl.c.
char k_get_preempt (void)
Get preempt or non preempt
Returns
: current state: 1 preempt sch. 0 non preempt
Definition at line 1063 of file krnl.c.
References krnl_preempt_flag.
int k_init (int nrTask, int nrSem, int nrMsg)
Initialise KRNL. First function to be called. You have to give max number of tasks, semaphores and message queues you will use
Parameters
[in] nrTask ...
[in] nrSem ...
[in] nrMsg ...
Definition at line 913 of file krnl.c.
References AQ, DMY_PRIO, dmy_stk, DMY_STK_SZ, dummy_task(), k_crt_sem(), k_crt_task(), k_err_cnt, k_msg, k_running, k_sem, k_task, k_t::next, pAQ, k_t::pred, k_t::prio, and QHD_PRIO.
char k_receive (struct k_msg_t * pB, void * el, int timeout, int * lost_msg)
Receive data (one element of el_size)in the ringbuffer if there are data DONE BY COPY !
Parameters
[in] pB Ref to message buffer
[out] el Reference to where data shall be copied to at your site
[in] timeout Max time you want to wait on data, -1: never, 0: forever, positive: nr of KRNL timer quants
[out] lost_msg nr of lost messages since last receive. will clip at 10000. If lost_msg ptr is NULL then overrun counter is not reset to 0.
Returns
0: operation did succed, -1: no data in ringbuffer
Remarks
only to be called after start of KRNL
Definition at line 805 of file krnl.c.
References k_msg_t::cnt, DI, EI, k_msg_t::el_size, ki_wait(), k_msg_t::lost_msg, k_msg_t::nr_el, k_msg_t::pBuf, k_msg_t::r, and k_msg_t::sem.
int k_sem_signals_lost (struct k_t * sem)
Returns how many signals has been lost on semaphore due to saturation
Parameters
[in] sem semaphore handle
Returns
nr of signals lost
Remarks
only to be called after start of KRNL
Definition at line 685 of file krnl.c.
References k_t::clip, DI, and EI.
char k_send (struct k_msg_t * pB, void * el)
Put data (one element of el_size)in the ringbuffer if there are room for it. DONE BY COPY !
Parameters
[in] pB Ref to message buffer
[in] el Reference to data to be put in buffer. Size if already given in k_crt_send
Returns
0: operation did succed, -1: no room in ringbuffer
Remarks
only to be called after start of KRNL
k_send does not block if no space in buffer. Instead -1 is returned
Definition at line 749 of file krnl.c.
References DI, EI, ki_send(), and ki_task_shift().
char k_set_preempt (char on)
Set preempt or non preempt on : 1: preempt on, 0: off 2: no change
Returns
: current state: 1 preempt sch. 0 non preempt
Definition at line 1054 of file krnl.c.
References krnl_preempt_flag.
int k_set_prio (char prio)
change priority of calling task)
Parameters
[in] prio new prio, Priority 1: highest (QHEAD_PRIO-1): lowest
Returns
: 0: ok, -1: KRNL not running, -2: illegal value
Remarks
only to be called after start of KRNL
Definition at line 463 of file krnl.c.
References deQ(), DI, DMY_PRIO, EI, k_running, ki_task_shift(), k_t::prio, and prio_enQ().
int k_set_sem_timer (struct k_t * sem, int val)
attach a timer to the semaphore so KRNL will signal the semaphore with regular intervals. Can be used for cyclic real time run of a task.
Parameters
[in] sem semaphore handle
[in] val interval in quant of KRNL ticks (0: disable cyclic timer, 1,2,3... cyclic quant)
Returns
-1: negative val, 0. ok
Remarks
only to be called after start of KRNL
Definition at line 528 of file krnl.c.
References k_t::cnt2, k_t::cnt3, DI, and EI.
int k_signal (struct k_t * sem)
Signal a semaphore. Task shift will task place if a task is started by the signal and has higher priority than you.
Parameters
[in] sem semaphore handle
Returns
0: ok , -1: max value of semaphore reached
Remarks
The ki_ indicates that interrups is NOT enabled when leaving ki_signal
only to be called after start of KRNL
Definition at line 568 of file krnl.c.
References DI, EI, ki_signal(), and ki_task_shift().
int k_sleep (int time)
Set task asleep for a number of ticks.
Parameters
[in] time nr of ticks to sleep < 0
Remarks
only to be called after start of KRNL
Definition at line 432 of file krnl.c.
References k_wait().
int k_start (int tm)
start KRNL with tm tick speed (1= 1 msec, 5 = 5 msec)
Parameters
[in] tm Tick length in milli seconds(1..10,20,30..10000
Returns
-1-333 nr of k_Crt calls taht went wrong. krnl did not start -555 negative tick parm value -666 bad tick quant (legal is 1-10,20,30-10000
Remarks
only to be called after init of KRNL
KRNL WILL NOT START IF YOU HAVE TRIED TO CREATE MORE TASKS/SEMS/MSG QS THAN YOU HAVE ALLOCATED SPACE FOR IN k_init !!!
Definition at line 948 of file krnl.c.
References k_t::cnt1, COUNTMAX, DI, DIVV, EI, fakecnt, fakecnt_preset, k_err_cnt, k_running, ki_task_shift(), main_el, PRESCALE, SCL, TCCRxA, TCCRxB, tcntValue, TCNTx, TIMSKx, and TOIEx.
int k_stk_chk (struct k_t * t)
returns nr of unbytes bytes on stak. For chekking if stak is too big or to small...
Parameters
[in] t Reference to task (by task handle) If null then yourself
Returns
: nr of unused bytes on stak (int)
Remarks
only to be called after start of KRNL
no chk of if it is a valid task
int k_stop (int exitVal)
stop KRNL
Parameters
exitVal] Will be returned in k_start to creator (old main)
Remarks
only to be called after k_start
you will only return from k_stop if krnl is not running
Definition at line 1024 of file krnl.c.
References k_t::cnt1, DI, EI, k_running, ki_task_shift(), main_el, k_t::next, TIMSKx, and TOIEx.
int k_tmrInfo (void)
returns which timer is used
Returns
0,1,2,3,4,5 ...
Definition at line 1047 of file krnl.c.
References KRNLTMR.
int k_unused_stak (struct k_t * t)
Returns amount of unused stak t . Ptr to taskdescriptor. If NULL it is yourself
Returns
: amount of unused stak(in bytes)
Remarks
: a watermark philosophy is used
Definition at line 440 of file krnl.c.
References k_t::cnt1, DI, EI, and STAK_HASH.
int k_wait (struct k_t * sem, int timeout)
Wait on a semaphore. Task shift will task place if you are blocked.
Parameters
[in] sem semaphore handle
[in] timeout "<0" you will be started after timeout ticks, "=0" wait forever "-1" you will not wait
Returns
0: ok , -1: timeout has occured, -2 no wait bq timeout was -1 and semaphore was negative
Remarks
only to be called after start of KRNL
Definition at line 635 of file krnl.c.
References k_t::cnt1, k_t::cnt2, k_t::cnt3, deQ(), DI, EI, enQ(), and ki_task_shift().
Referenced by k_sleep(), and k_wait_lost().
int k_wait_lost (struct k_t * sem, int timeout, int * lost)
Wait on a semaphore. Task shift will task place if you are blocked.
Parameters
[in] sem semaphore handle
[in] timeout "<0" you will be started after timeout ticks, "=0" wait forever "-1" you will not wait
[out] lost if not eq NULL it resturns how many signals has been lost
Returns
0: ok , -1: timeout has occured, -2 no wait bq timeout was -1 and semaphore was negative
Remarks
only to be called after start of KRNL
Definition at line 673 of file krnl.c.
References k_t::clip, DI, and k_wait().
int ki_nowait (struct k_t * sem)
Do a wait if no blocking will occur.
Parameters
[in] sem semaphore handle
Returns
0: ok , -1: could do wait bw blocking would have taken place
Remarks
The ki_ indicates that interrups is NOT enabled when leaving ki_nowait
only to be called after start of KRNL
Definition at line 587 of file krnl.c.
References k_t::cnt1, and DI.
Referenced by ki_receive().
char ki_receive (struct k_msg_t * pB, void * el, int * lost_msg)
Receive data (one element of el_size)in the ringbuffer if there are data DONE BY COPY ! No blocking if no data Interrupt will not be enabled after ki_receive
Parameters
[in] pB Ref to message buffer
[out] el Reference to where data shall be copied to at your site
[out] lost_msg nr of lost messages since last receive. will clip at 10000. If lost_msg ptr is NULL then overrun counter is not reset to 0
Returns
0: operation did succed, -1: no data in ringbuffer
Remarks
can be used from ISR
only to be called after start of KRNL
Definition at line 769 of file krnl.c.
References k_msg_t::cnt, DI, k_msg_t::el_size, ki_nowait(), k_msg_t::lost_msg, k_msg_t::nr_el, k_msg_t::pBuf, k_msg_t::r, and k_msg_t::sem.
int ki_semval (struct k_t * sem)
returns value of semaphore
Parameters
[in] sem semaphore handle
Returns
0: semaphore value, negative: tasks are waiting, 0: nothing, positive: ...
Remarks
only to be called after start of KRNL
Definition at line 697 of file krnl.c.
References k_t::cnt1, and DI.
char ki_send (struct k_msg_t * pB, void * el)
Put data (one element of el_size)in the ringbuffer if there are room for it. Intended for ISR use DONE BY COPY !
Parameters
[in] pB Ref to message buffer
[in] el Reference to data to be put in buffer. Size if already given in k_crt_send
Returns
0: operation did succed, -1: no room in ringbuffer
Remarks
Interrupt will not enabled upon leaving, so ki_send is intended to be used from an ISR
only to be called before start of KRNL
Definition at line 713 of file krnl.c.
References k_msg_t::cnt, k_msg_t::el_size, ki_signal(), k_msg_t::lost_msg, k_msg_t::nr_el, k_msg_t::pBuf, k_msg_t::sem, and k_msg_t::w.
Referenced by k_send().
int ki_signal (struct k_t * sem)
Signal a semaphore. Can be called from an ISR when interrupt is disabled. No task shift will occur - only queue manipulation.
Parameters
[in] sem semaphore handle
Returns
0: ok , -1: max value of semaphore reached
Remarks
only to be called after start of KRNL
Definition at line 546 of file krnl.c.
References k_t::clip, k_t::cnt1, k_t::cnt2, deQ(), DI, k_t::maxv, k_t::next, and prio_enQ().
Referenced by ISR(), k_signal(), and ki_send().
void ki_task_shift (void)
issues a task shift - handle with care Not to be used by normal user
Referenced by k_round_robbin(), k_send(), k_set_prio(), k_signal(), k_start(), k_stop(), k_wait(), and ki_wait().
int ki_wait (struct k_t * sem, int timeout)
Like k_wait with the exception interrupt is NOT enabled when leaving
Parameters
[in] sem semaphore handle
[in] timeout "<0" you will be started after timeout ticks, "=0" wait forever "-1" you will not wait
Returns
0: ok , -1: could do wait bw blocking would have taken place
Remarks
The ki_ indicates that interrups is NOT enabled when leaving ki_wait
only to be called after start of KRNL
Definition at line 602 of file krnl.c.
References k_t::cnt1, k_t::cnt2, k_t::cnt3, deQ(), DI, enQ(), and ki_task_shift().
Referenced by k_receive().
Variable Documentation
struct k_t AQ
Definition at line 151 of file krnl.c.
Referenced by k_init().
volatile char bugblink
char dmy_stk[DMY_STK_SZ]
Definition at line 166 of file krnl.c.
Referenced by k_init().
volatile char k_err_cnt
Definition at line 169 of file krnl.c.
Referenced by k_crt_sem(), k_crt_send_Q(), k_crt_task(), k_init(), and k_start().
int k_msg
Definition at line 163 of file krnl.c.
Referenced by k_crt_send_Q(), and k_init().
volatile char k_running
Definition at line 169 of file krnl.c.
Referenced by ISR(), k_crt_sem(), k_crt_send_Q(), k_crt_task(), k_init(), k_set_prio(), k_start(), and k_stop().
int k_sem
Definition at line 163 of file krnl.c.
Referenced by k_crt_sem(), k_crt_send_Q(), and k_init().
int k_task
Definition at line 163 of file krnl.c.
Referenced by k_crt_task(), and k_init().
volatile char krnl_preempt_flag
Definition at line 168 of file krnl.c.
Referenced by ISR(), k_get_preempt(), and k_set_preempt().
struct k_t main_el
Definition at line 151 of file krnl.c.
Referenced by k_start(), and k_stop().
char nr_sem
Definition at line 164 of file krnl.c.
Referenced by ISR(), k_crt_sem(), and k_crt_send_Q().
char nr_send
Definition at line 164 of file krnl.c.
Referenced by k_crt_send_Q().
char nr_task
Definition at line 164 of file krnl.c.
Referenced by ISR(), and k_crt_task().
struct k_t * pAQ
Definition at line 151 of file krnl.c.
Referenced by k_init().
struct k_t * pDmy
Definition at line 151 of file krnl.c.
struct k_t * pRun
Definition at line 151 of file krnl.c.
struct k_t * pSleepSem
Definition at line 151 of file krnl.c.
struct k_t * sem_pool
Definition at line 151 of file krnl.c.
Referenced by ISR().
struct k_msg_t* send_pool
Definition at line 161 of file krnl.c.
struct k_t* task_pool
Definition at line 151 of file krnl.c.
Referenced by ISR().